# データベースへの接続設定(ローカルのPostgreSQLを指定)
spring.datasource.url=${DB-URL:jdbc:postgresql://ep-cold-mouse-ao9fql9i-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.username=${DB_USER:neondb_owner}

spring.datasource.password=${DB_PASSWORD:npg_CEvIV4f7pdDA}

# PostgreSQL用の設定
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernateが自動的にテーブルを作成・更新する設定
spring.jpa.hibernate.ddl-auto=update

# 実行されるSQLをログに表示する（デバック用）
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
